# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\x12\x05\x63hord\"X\n\x04\x44\x61ta\x12#\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x15.chord.Data.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1a\n\x07HashKey\x12\x0f\n\x07hashKey\x18\x01 \x01(\r\"\x1e\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\t\"*\n\x05NodeI\x12\n\n\x02id\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\t\x12\t\n\x01i\x18\x03 \x01(\r\"8\n\x06NodeII\x12\x0b\n\x03rid\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\r\x12\n\n\x02ip\x18\x03 \x01(\t\x12\t\n\x01i\x18\x04 \x01(\r\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xb6\x06\n\x08\x63hordRPC\x12*\n\rget_successor\x12\x0c.chord.Empty\x1a\x0b.chord.Node\x12,\n\x0fget_predecessor\x12\x0c.chord.Empty\x1a\x0b.chord.Node\x12\x33\n\x14\x66ind_predecessor_rpc\x12\x0e.chord.HashKey\x1a\x0b.chord.Node\x12\x31\n\x12\x66ind_successor_rpc\x12\x0e.chord.HashKey\x1a\x0b.chord.Node\x12$\n\x08get_data\x12\x0b.chord.Node\x1a\x0b.chord.Data\x12%\n\x08set_data\x12\x0b.chord.Data\x1a\x0c.chord.Empty\x12\x36\n\x18\x63hange_finger_create_rpc\x12\x0c.chord.NodeI\x1a\x0c.chord.Empty\x12\x37\n\x18\x63hange_finger_delete_rpc\x12\r.chord.NodeII\x1a\x0c.chord.Empty\x12/\n\x12\x63hange_predecessor\x12\x0b.chord.Node\x1a\x0c.chord.Empty\x12-\n\x10\x63hange_successor\x12\x0b.chord.Node\x1a\x0c.chord.Empty\x12,\n\x0b\x64\x65l_key_rpc\x12\x0f.chord.KeyValue\x1a\x0c.chord.Empty\x12,\n\x0b\x61\x64\x64_key_rpc\x12\x0f.chord.KeyValue\x1a\x0c.chord.Empty\x12/\n\x0bget_key_rpc\x12\x0f.chord.KeyValue\x1a\x0f.chord.KeyValue\x12/\n\x0e\x64irect_add_rpc\x12\x0f.chord.KeyValue\x1a\x0c.chord.Empty\x12/\n\x0e\x64irect_del_rpc\x12\x0f.chord.KeyValue\x1a\x0c.chord.Empty\x12\x32\n\x0e\x64irect_get_rpc\x12\x0f.chord.KeyValue\x1a\x0f.chord.KeyValue\x12\'\n\tleave_rpc\x12\x0c.chord.Empty\x1a\x0c.chord.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATA_DATAENTRY']._options = None
  _globals['_DATA_DATAENTRY']._serialized_options = b'8\001'
  _globals['_DATA']._serialized_start=22
  _globals['_DATA']._serialized_end=110
  _globals['_DATA_DATAENTRY']._serialized_start=67
  _globals['_DATA_DATAENTRY']._serialized_end=110
  _globals['_HASHKEY']._serialized_start=112
  _globals['_HASHKEY']._serialized_end=138
  _globals['_NODE']._serialized_start=140
  _globals['_NODE']._serialized_end=170
  _globals['_NODEI']._serialized_start=172
  _globals['_NODEI']._serialized_end=214
  _globals['_NODEII']._serialized_start=216
  _globals['_NODEII']._serialized_end=272
  _globals['_KEYVALUE']._serialized_start=274
  _globals['_KEYVALUE']._serialized_end=312
  _globals['_EMPTY']._serialized_start=314
  _globals['_EMPTY']._serialized_end=321
  _globals['_CHORDRPC']._serialized_start=324
  _globals['_CHORDRPC']._serialized_end=1146
# @@protoc_insertion_point(module_scope)
